# Generated by Django 2.2 on 2020-07-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='created_by',
            new_name='added_by',
        ),
    ]
