# Generated by Django 2.2 on 2020-07-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20200708_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_posts', to='app_one.User'),
        ),
    ]
